Package: glib
Version: 2.18.4
Revision: 2
Maintainer: Marmalade Package Team <packages@marmalademail.com>
Mkbs: glib.mkb
Libraries: glib
Description: |
 GLib is a library containing many useful C routines for things such
 as trees, hashes, lists, and strings.  It is a useful general-purpose
 C library used by projects such as GTK+, GIMP, and GNOME.
 .
 This package contains the shared libraries.
Contents:
 - upstream/glib/glib.h : h/glib.h
 - upstream/gobject/*.h : h/gobject
 - upstream/glib/*.h : h/glib
 - upstream/gio/*.h : h/gio
 - glibconfig.h : h/glibconfig.h
Contents-Source:
 - glib.mkf
 - glib.mkb
 - glib.defines.txt
 - glibconfig.h
 - internal/config.h
